modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issues_url}" #optional: none

[[mods]]
  modId="${mod_id}"
  version="${version}" #optional: "1"
  displayName="${mod_name}" #optional: modId
  description='''${mod_description}''' # optional: "MISSING DESCRIPTION"
  logoFile="assets/${mod_id}/icon.png" #optional: none
  features={ java_version="[17,)" }
  credits="${mod_credits}" #optional: none
  authors="${mod_author}" #optional: none
  displayURL="${homepage_url}" #optional: none

[[mixins]]
  config="chatnotify.mixins.json"
[[mixins]]
  config="chatnotify.neoforge.mixins.json"

[[dependencies.${mod_id}]] #optional
  modId="neoforge"
  mandatory=true
  versionRange="${neoforge_loader_version_range}"
  ordering="NONE" #optional: "NONE"
  side="CLIENT" #optional: "BOTH"

[[dependencies.${mod_id}]]
  modId="minecraft"
  mandatory=true
  versionRange="${minecraft_version_range}"
  ordering="NONE" #optional: "NONE"
  side="BOTH" #optional: "BOTH"

# https://docs.neoforged.net/docs/gettingstarted/modfiles/
# https://docs.neoforged.net/docs/misc/updatechecker/